name: .NET Core

on:
  push:
    branches: [ feature/global-cli-flags ]
  pull_request:
    branches: [ feature/global-cli-flags ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
