name: Release

on:
  release:
    types:
     - edited
     - created

jobs:
  generate:
    name: Create release artifacts
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build/Publish
      run: dotnet publish --configuration Release /property:GenerateFullPaths=true
    - name: Upload artifacts
      run: pwsh -command "${{github.workspace}}\.github\scripts\upload-artifacts-release.ps1"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_PATH: ${{github.event.path}}
        GITHUB_REPOSITORY: ${{github.repository}}