name: Release

on:
  release:
    types:
     - edited
     - created

jobs:
  generate:
    name: Create release artifacts
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --configuration Release --no-restore 
    - name: Upload artifacts
      run: pwsh -command ".\$GITHUB_WORKSPACE\scripts\upload-artifacts-release.ps1"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_PATH: ${{ GITHUB_EVENT_PATH }}
        GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
        ARTIFACTS_DIRECTORY: 'D:/a/azure-devops-migration-tools/azure-devops-migration-tools/src/MigrationTools.ConsoleFull/bin/Release/net472/publish/'